apiVersion: v1
kind: Service
metadata:
  name: health-monitor-svc
  namespace: ondc
  labels:
    app: health-monitor
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: health-monitor
  ports:
    - port: 3008
      targetPort: 3008
      name: http
