apiVersion: v1
kind: Service
metadata:
  name: log-aggregator-svc
  namespace: ondc
  labels:
    app: log-aggregator
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: log-aggregator
  ports:
    - port: 3009
      targetPort: 3009
      name: http
