apiVersion: v1
kind: Service
metadata:
  name: mock-server-svc
  namespace: ondc-simulation
  labels:
    app: mock-server
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: mock-server
  ports:
    - port: 3010
      targetPort: 3010
      name: http
