apiVersion: v1
kind: Service
metadata:
  name: simulation-engine-svc
  namespace: ondc-simulation
  labels:
    app: simulation-engine
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: simulation-engine
  ports:
    - port: 3011
      targetPort: 3011
      name: http
