apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  namespace: ondc
  labels:
    app: admin
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: admin
  ports:
    - port: 3003
      targetPort: 3003
      name: http
