apiVersion: v1
kind: Service
metadata:
  name: bpp-svc
  namespace: ondc
  labels:
    app: bpp
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: bpp
  ports:
    - port: 3005
      targetPort: 3005
      name: http
