apiVersion: v1
kind: Service
metadata:
  name: docs-svc
  namespace: ondc
  labels:
    app: docs
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: docs
  ports:
    - port: 3000
      targetPort: 3000
      name: http
