apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: ondc
  labels:
    app: gateway
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: gateway
  ports:
    - port: 3002
      targetPort: 3002
      name: http
