apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  namespace: ondc
  labels:
    app: vault
    app.kubernetes.io/part-of: ondc
spec:
  selector:
    app: vault
  ports:
    - port: 3006
      targetPort: 3006
      name: http
